import * as THREE from 'three';
import {OrbitControls} from './OrbitControls.js';
import {createStellarEffects} from './stellar-effects.js';
import {createNarrator} from './narration.js';
import {createInterior,interiorLayers} from './interior.js';
const $=id=>document.getElementById(id);
const common=[['Stellar nursery','A cold cloud of gas and dust. Gravity pulls denser pockets inward, beginning the story of a new star.','10–30 K','Gravity','Cloud temperature'],['Protostar','As the cloud contracts, its centre heats up. A young star gathers material; sustained hydrogen fusion has not yet begun.','Warming rapidly','Contraction','CORE CONDITIONS']];
const tracks={sun:{name:'Sun-like star',mass:'1 solar mass',end:'White dwarf',intro:'A long, steady life. A quiet, glowing farewell.',ages:[0,.03,.05,10,12,12.01],unit:'billion',data:[...common,['Main sequence','Hydrogen fuses into helium in the core. Outward pressure balances gravity. Our Sun is in this long, stable chapter.','≈ 5,800 K','Hydrogen fusion'],['Red giant','Core hydrogen runs low. The core contracts while outer layers swell and cool. Later, helium fusion makes carbon and oxygen.','≈ 3,500 K','Shell & helium fusion'],['Planetary nebula','The star sheds its outer layers. Light from the exposed hot core makes the expanding gas glow. Despite the name, no planets are involved.','≈ 100,000 K','Outer layers escape','EXPOSED CORE'],['White dwarf','An Earth-sized stellar core remains. With no sustained fusion, it slowly cools for billions of years. A single Sun-like star does not become a supernova.','Initially very hot','Slow cooling','REMNANT TEMPERATURE']]},massive:{name:'Massive star',mass:'15 solar masses',end:'Neutron star',intro:'A brilliant, brief life. An extraordinary remnant.',ages:[0,.05,.1,11,12,12.00001],unit:'million',data:[...common,['Main sequence','A massive star burns hot and blue. Its large fuel supply is used much faster than the Sun’s, giving it a far shorter life.','≈ 30,000 K','Hydrogen fusion'],['Red supergiant','The star expands enormously. Successive fusion stages build heavier elements in its interior, eventually forming an iron core.','≈ 3,500 K','Advanced fusion'],['Supernova','Iron fusion cannot support the core. It collapses, launching a shock that can eject the outer layers in a powerful explosion.','Extremely hot','Core collapse','EJECTA'],['Neutron star','In this example, collapse leaves a compact ball of neutrons roughly city-sized. Its magnetic beams can appear as pulses as it spins.','Initially ≈ 1 million K','Degeneracy pressure']]},heavy:{name:'Very massive star',mass:'30 solar masses',end:'Black hole',intro:'An intense life. A boundary beyond which light cannot escape.',ages:[0,.03,.06,5,6,6.00001],unit:'million',data:[...common,['Main sequence','This very massive star shines intensely, using its hydrogen quickly. Strong stellar winds carry away part of its mass.','≈ 40,000 K','Hydrogen fusion'],['Evolved massive star','The core builds heavier elements as fuel runs out. Its envelope and appearance depend strongly on winds and composition.','Varies with mass loss','Advanced fusion'],['Core collapse','The core collapses. This illustrated path includes an explosion, but some massive stars may form black holes with little visible supernova.','Extremely hot','Core collapse','EJECTA'],['Black hole','The remaining core collapses beyond an event horizon. Light cannot escape from inside. Any glowing disk is hot surrounding gas, not the black hole itself.','No stellar surface','Extreme gravity']]}};
let selected='massive',progress=.4,playing=false,lastStage=-1,lastTrack='',elapsed=0;
let narrator;
let inside=false,peel=100,selectedLayer=0,interiorKey='',layers=[];
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});}catch(e){$('status').textContent='This device could not start 3D graphics. Try a browser with WebGL enabled.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.xr.enabled=true;renderer.setClearColor(0x050811,0);$('universe').appendChild(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(50,1,.05,500);camera.position.set(0,1.6,12);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.6,0);controls.enableDamping=true;controls.minDistance=5;controls.maxDistance=24;controls.enablePan=false;
const system=new THREE.Group();system.position.set(0,1.6,0);scene.add(system);
const noise=`float hash(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);}float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}float fbm(vec3 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=a*noise(p);p=p*2.03;a*=.5;}return v;}`;
const starMat=new THREE.ShaderMaterial({uniforms:{time:{value:0},tint:{value:new THREE.Color('#8ecbff')},dark:{value:0}},vertexShader:`varying vec3 vP;varying vec3 vN;void main(){vP=position;vN=normal;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 vP;varying vec3 vN;uniform float time;uniform vec3 tint;uniform float dark;${noise}void main(){float n=fbm(vP*9.+vec3(time*.12));float fine=fbm(vP*36.-vec3(time*.2));float bright=.5+n*.9+smoothstep(.48,.8,fine)*.8;gl_FragColor=vec4(mix(tint*bright,vec3(.001),dark),1.);}`});
const star=new THREE.Mesh(new THREE.SphereGeometry(1,80,56),starMat);system.add(star);
const glowMat=new THREE.ShaderMaterial({uniforms:{tint:{value:new THREE.Color('#7bbfff')},strength:{value:.5}},vertexShader:`varying vec3 n;varying vec3 eye;void main(){vec4 p=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);eye=normalize(-p.xyz);gl_Position=projectionMatrix*p;}`,fragmentShader:`varying vec3 n;varying vec3 eye;uniform vec3 tint;uniform float strength;void main(){float g=pow(abs(dot(normalize(n),normalize(eye))),2.);gl_FragColor=vec4(tint,g*strength);}`,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,side:THREE.BackSide});
const glow=new THREE.Mesh(new THREE.SphereGeometry(1,48,32),glowMat);system.add(glow);
let seed=317;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const bg=new THREE.BufferGeometry(),bp=[],bc=[];for(let i=0;i<2400;i++){const a=rand()*Math.PI*2,u=rand()*2-1,r=60+rand()*80;bp.push(Math.sqrt(1-u*u)*Math.cos(a)*r,u*r,Math.sqrt(1-u*u)*Math.sin(a)*r);const c=.3+rand()*.7;bc.push(c*.8,c*.88,c);}bg.setAttribute('position',new THREE.Float32BufferAttribute(bp,3));bg.setAttribute('color',new THREE.Float32BufferAttribute(bc,3));scene.add(new THREE.Points(bg,new THREE.PointsMaterial({size:.11,vertexColors:true,sizeAttenuation:true})));
const jetgroup=new THREE.Group();for(const sign of [-1,1]){const jet=new THREE.Mesh(new THREE.ConeGeometry(.35,4,32,1,true),new THREE.MeshBasicMaterial({color:0x7cbfff,transparent:true,opacity:.2,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false}));jet.position.y=sign*2;jet.rotation.z=sign<0?Math.PI:0;jetgroup.add(jet);}jetgroup.rotation.z=.4;system.add(jetgroup);
const radiusSets={sun:[.04,.55,1.1,2.05,.25,.2],massive:[.04,.65,1.35,2.35,.15,.17],heavy:[.04,.7,1.5,2.25,.15,.65]};
const effects=createStellarEffects(system,star,glow);
const interior=createInterior(system);
function state(){const x=progress*5;return {s:Math.min(5,Math.floor(x+1e-7)),f:x-Math.floor(x),track:tracks[selected]};}
function setProgress(p,seek=true){if(seek)effects.seek();progress=THREE.MathUtils.clamp(p,0,1);$('time').value=Math.round(progress*1000);updateUI();if(seek&&narrator?.active)narrator.seek(selected,state().s);}
function choose(key){selected=key;$('star').value=key;lastStage=-1;setProgress(0);}
function updateUI(){const {s,f,track}=state(),d=track.data[s];const a=track.ages[s]+(s<5?(track.ages[s+1]-track.ages[s])*f:0);$('age').textContent=s===0&&progress===0?'Before a star is born':`≈ ${a<.01?a.toFixed(3):a.toFixed(2)} ${track.unit} years`;
if(s!==lastStage||selected!==lastTrack){$('chapter').textContent=`CHAPTER ${String(s+1).padStart(2,'0')} / 06`;$('stageTitle').textContent=d[0];$('description').textContent=d[1];$('temperature').textContent=d[2];$('process').textContent=d[3];$('factLabel').textContent=d[4]||'SURFACE TEMPERATURE';$('journey').textContent=track.intro;$('destination').textContent=track.end;$('stages').replaceChildren(...track.data.map((v,i)=>{const b=document.createElement('button');b.textContent=v[0];b.className=i===s?'active':'';b.setAttribute('aria-label','Travel to '+v[0]);b.onclick=()=>setProgress(i/5);return b;}));lastStage=s;lastTrack=selected;}updateInteriorUI();drawPanel();}
function togglePlay(){if(narrator?.active){narrator.toggle();return;}playing=!playing;$('play').textContent=playing?'Ⅱ Pause':'▶ Play journey';if(playing&&progress===1)setProgress(0);drawPanel();}
$('star').onchange=e=>choose(e.target.value);$('time').oninput=e=>setProgress(Number(e.target.value)/1000);$('play').onclick=togglePlay;$('back').onclick=()=>setProgress((Math.ceil(progress*5)-1)/5);$('next').onclick=()=>setProgress((Math.floor(progress*5)+1)/5);$('reset').onclick=()=>{camera.position.set(0,1.6,12);controls.target.set(0,1.6,0);controls.update();};$('science').onclick=()=>$('notes').showModal();$('close').onclick=()=>$('notes').close();

function updateInteriorUI(){
  const {s}=state(),key=selected+s;
  if(key!==interiorKey){interiorKey=key;layers=interiorLayers(selected,s);selectedLayer=0;interior.setLayers(layers);}
  if(!layers.length)inside=false;
  $('inside').textContent=inside?'Close cutaway':'Look inside a star';
  $('inside').setAttribute('aria-pressed',String(inside));
  $('inside').disabled=!layers.length;
  $('insideHint').textContent=layers.length?'Peel back the layers to find the energy source.':'Choose Protostar, Main sequence or Giant to explore inside.';
  $('interiorControls').hidden=!inside;
  const layoutChanged=$('app').classList.contains('inside')!==inside;
  $('app').classList.toggle('inside',inside);if(layoutChanged)resize();
  $('peel').value=peel;$('peelValue').textContent=peel+'% open';
  $('layerButtons').replaceChildren(...layers.map((l,i)=>{
    const b=document.createElement('button');b.textContent=l.name;b.style.setProperty('--layer',l.color);
    b.setAttribute('aria-pressed',String(i===selectedLayer));b.onclick=()=>selectLayer(i);return b;
  }));
  $('layerText').textContent=layers[selectedLayer]?.text||'';
  $('fusionBadge').textContent=layers[selectedLayer]?.fusion?'FUSION RELEASES ENERGY':'NO FUSION IN THIS LAYER';
}
function toggleInside(){
  if(!layers.length)return;
  inside=!inside;if(inside){if(narrator?.active)narrator.stop();playing=false;$('play').textContent='▶ Play journey';peel=100;}
  updateInteriorUI();drawPanel();
}
function selectLayer(i){selectedLayer=(i+layers.length)%layers.length;peel=100;updateInteriorUI();drawPanel();}
function setPeel(value){peel=THREE.MathUtils.clamp(value,0,100);$('peel').value=peel;$('peelValue').textContent=Math.round(peel)+'% open';drawPanel();}
$('inside').onclick=toggleInside;$('peel').oninput=e=>setPeel(Number(e.target.value));
// The floating observatory panel is part of the 3D scene, so it remains usable in VR.
const panelCanvas=document.createElement('canvas');panelCanvas.width=1400;panelCanvas.height=680;const ctx=panelCanvas.getContext('2d');const panelTexture=new THREE.CanvasTexture(panelCanvas);panelTexture.colorSpace=THREE.SRGBColorSpace;const panel=new THREE.Mesh(new THREE.PlaneGeometry(3.1,1.5),new THREE.MeshBasicMaterial({map:panelTexture,side:THREE.DoubleSide}));panel.position.set(0,.15,-3.1);panel.rotation.x=-.22;panel.visible=false;scene.add(panel);
function wrap(text,x,y,maxWidth,lineHeight){let line='';for(const word of text.split(' ')){const trial=line+word+' ';if(ctx.measureText(trial).width>maxWidth){ctx.fillText(line,x,y);line=word+' ';y+=lineHeight;}else line=trial;}ctx.fillText(line,x,y);}
function drawPanel(){const {s,track}=state();ctx.fillStyle='#101b2c';ctx.fillRect(0,0,1400,680);ctx.fillStyle='#edc38b';ctx.font='24px sans-serif';ctx.fillText('STELLAR VOYAGER  /  '+track.name.toUpperCase(),48,55);ctx.fillStyle='#344359';ctx.fillRect(1030,14,325,58);ctx.fillStyle='#fff';ctx.fillText(narrator?.language==='hi'?'आवाज़: हिन्दी ⇄':'Voice: English ⇄',1050,52);ctx.font='bold 46px sans-serif';ctx.fillStyle='#ffffff';ctx.fillText(inside?layers[selectedLayer].name:track.data[s][0],48,123);ctx.font='27px sans-serif';ctx.fillStyle='#c0cde1';wrap(inside?layers[selectedLayer].text:(narrator?.active?narrator.caption:track.data[s][1]),48,175,1300,37);ctx.fillStyle='#c1cde0';ctx.font='24px sans-serif';ctx.fillText(inside?'CUTAWAY · Colours and layer sizes are illustrative':$('age').textContent+'  •  Time & size compressed',48,310);ctx.fillStyle='#344359';ctx.fillRect(55,355,1290,25);ctx.fillStyle='#edc38b';ctx.fillRect(55,355,1290*(inside?peel/100:progress),25);ctx.beginPath();ctx.arc(55+1290*(inside?peel/100:progress),367,20,0,Math.PI*2);ctx.fill();ctx.fillStyle='#b9c8dc';ctx.font='23px sans-serif';ctx.fillText(inside?'SURFACE':'BIRTH',55,420);ctx.fillText(inside?'CORE':'REMNANT',1220,420);const labels=inside?['‹ Layer','Layer ›','Exterior',playing?'Pause':'Play']:['Sun-like','Massive','Very massive',playing?'Pause':'Play'];labels.forEach((v,i)=>{ctx.fillStyle=i===['sun','massive','heavy'].indexOf(selected)?'#755c3b':'#25364f';ctx.fillRect(45+i*337,468,315,85);ctx.fillStyle='#fff';ctx.font='30px sans-serif';ctx.fillText(v,70+i*337,521);});ctx.font='23px sans-serif';ctx.fillStyle='#9db0cb';ctx.fillStyle='#344359';ctx.fillRect(45,574,645,70);ctx.fillRect(710,574,645,70);ctx.fillStyle='#fff';ctx.fillText(narrator?.active?'Stop guided tour':'Start guided tour',70,618);ctx.fillStyle=layers.length?'#fff':'#8292aa';ctx.fillText(inside?'Close cutaway':layers.length?'Look inside a star':'Interior: choose a stellar stage',735,618);panelTexture.needsUpdate=true;}
const raycaster=new THREE.Raycaster(),rotation=new THREE.Matrix4();const controllers=[];
for(let i=0;i<2;i++){const controller=renderer.xr.getController(i);scene.add(controller);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,0,-1)]),new THREE.LineBasicMaterial({color:0xeec58d}));line.scale.z=8;controller.add(line);controller.addEventListener('selectstart',()=>controller.userData.pressed=true);controller.addEventListener('selectend',()=>controller.userData.pressed=false);controllers.push(controller);}
function interact(controller){rotation.identity().extractRotation(controller.matrixWorld);raycaster.ray.origin.setFromMatrixPosition(controller.matrixWorld);raycaster.ray.direction.set(0,0,-1).applyMatrix4(rotation);const hit=raycaster.intersectObject(panel)[0];if(!hit)return;const x=hit.uv.x*1400,y=(1-hit.uv.y)*680;if(y>14&&y<72&&x>1030&&!controller.userData.clicked){narrator.setLanguage(narrator.language==='hi'?'en':'hi');controller.userData.clicked=true;}else if(y>574&&y<644&&!controller.userData.clicked){if(x<700)toggleGuide();else toggleInside();controller.userData.clicked=true;}else if(y>330&&y<435){if(inside)setPeel((x-55)/1290*100);else setProgress((x-55)/1290);}else if(y>468&&y<553&&!controller.userData.clicked){const i=Math.floor((x-45)/337);if(i>=0&&i<3){if(inside){if(i===2)toggleInside();else selectLayer(selectedLayer+(i===0?-1:1));}else choose(['sun','massive','heavy'][i]);}if(i===3)togglePlay();controller.userData.clicked=true;}}
let xrSession=null;$('vr').onclick=async()=>{if(xrSession){await xrSession.end();return;}try{if(!navigator.xr||!await navigator.xr.isSessionSupported('immersive-vr')){showStatus('For immersive VR, open this link in a compatible headset browser. You can explore in 3D here.');return;}xrSession=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor']});await renderer.xr.setSession(xrSession);}catch(e){showStatus('VR could not start. Check headset connection and browser permissions, then try again.');xrSession=null;}};
renderer.xr.addEventListener('sessionstart',()=>{controls.enabled=false;camera.position.set(0,1.6,0);system.position.set(0,2,-9);panel.visible=true;$('vr').textContent='Exit VR';});renderer.xr.addEventListener('sessionend',()=>{xrSession=null;panel.visible=false;system.position.set(0,1.6,0);controls.enabled=true;$('reset').click();$('vr').textContent='Enter VR ↗';});
let statusTimeout;function showStatus(text){$('status').textContent=text;clearTimeout(statusTimeout);statusTimeout=setTimeout(()=>$('status').textContent='',9000);}
function resize(){const w=$('app').clientWidth,h=$('app').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();if(w<700){camera.setViewOffset(w,h,0,120,w,h);}else camera.clearViewOffset();}addEventListener('resize',resize);resize();$('star').value=selected;setProgress(progress);$('status').textContent='';

narrator=createNarrator({
  onProgress:p=>setProgress(p,false),
  onChange:({active,paused,caption,language})=>{
    playing=active&&!paused;
    $('guide').textContent=active?'Stop guided tour':'♫ Start guided tour';
    $('guide').setAttribute('aria-pressed',String(active));
    $('captions').hidden=!active;$('captionText').textContent=caption;
    $('captionLabel').textContent=language==='hi'?(paused?'हिन्दी यात्रा · रुका हुआ':'हिन्दी यात्रा · सुनिए'):(paused?'GUIDED JOURNEY · PAUSED':'GUIDED JOURNEY · NARRATION');
    $('captionText').lang=language;$('language').value=language;
    $('play').textContent=playing?'Ⅱ Pause':'▶ Play journey';
    $('app').classList.toggle('guided',active);drawPanel();
  },
  onFinish:()=>showStatus('Journey complete. Choose another star or explore with the timeline.'),
  onError:showStatus
});
function toggleGuide(){if(narrator.active)narrator.stop();else {inside=false;updateInteriorUI();narrator.start(selected);}}
$('guide').onclick=toggleGuide;
$('language').onchange=e=>{narrator.setLanguage(e.target.value);try{localStorage.setItem('stellar-language',e.target.value);}catch{}};
try{if(localStorage.getItem('stellar-language')==='hi')narrator.setLanguage('hi');}catch{}

const clock=new THREE.Clock();let uiTick=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(!reduced)elapsed+=dt;if(narrator.active){uiTick+=dt;if(uiTick>.08){narrator.tick();uiTick=0;}}else if(playing){progress=Math.min(1,progress+dt/75);uiTick+=dt;if(uiTick>.08){setProgress(progress,false);uiTick=0;}if(progress>=1){playing=false;$('play').textContent='▶ Play journey';setProgress(1);}}
const {s,f}=state();const smooth=THREE.MathUtils.smoothstep(f,0,1),radii=radiusSets[selected];let r=THREE.MathUtils.lerp(radii[s],radii[Math.min(s+1,5)],smooth);star.scale.setScalar(r);star.visible=s>0||f>.1;star.rotation.y=elapsed*.04;starMat.uniforms.time.value=elapsed;const color=s>=3&&s<4?'#ff7735':s===5?(selected==='sun'?'#d8edff':'#a0caff'):selected==='sun'?'#ffc671':'#91bdff';starMat.uniforms.tint.value.set(color);starMat.uniforms.dark.value=s===5&&selected==='heavy'?1:0;glowMat.uniforms.tint.value.set(color);glow.scale.setScalar(r*1.27);glow.visible=star.visible&&!(s===5&&selected==='heavy');
jetgroup.visible=s===5&&selected==='massive';jetgroup.rotation.y=elapsed*.9;
effects.update({s,f,selected,time:elapsed,dt,radius:r,reduced,playing,pixelRatio:renderer.getPixelRatio(),inside});
interior.update({active:inside,peel,radius:r,time:elapsed,camera,selected:selectedLayer});if(inside){star.visible=false;glow.visible=false;}
if(renderer.xr.isPresenting){for(const c of controllers){if(c.userData.pressed)interact(c);else c.userData.clicked=false;}}else controls.update();renderer.render(scene,camera);});
window.stellarVoyager={getState:()=>({star:selected,progress,stage:state().track.data[state().s][0],playing,guided:narrator.active}),choose,setProgress};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'set_stellar_journey',description:'Choose a stellar track and position on its stage-based timeline.',inputSchema:{type:'object',properties:{star:{type:'string',enum:['sun','massive','heavy']},progress:{type:'number',minimum:0,maximum:1}},required:['star','progress'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Object.hasOwn(tracks,input.star)||typeof input.progress!=='number'||!Number.isFinite(input.progress)||input.progress<0||input.progress>1)throw new Error('Choose a valid star and progress between 0 and 1.');choose(input.star);setProgress(input.progress);return window.stellarVoyager.getState();}})).catch(()=>{});}catch{}}
